### ISSUE TITLE
优化代码

### ISSUE THREAD

**Issue by CnKyo** [ysyplay/YsyRadio#1]
核心加载方法改为数组加载更好一点,便于构造UI    [YsyRadioGroup addToView:self.view select:^(YsyRadio *radio) {
        label.text = [NSString stringWithFormat:@"name:%@  val:%@",radio.name,radio.val];
    } radios:@[radio1,radio2,radio3,radio4,radio5,radio6]];

**Comment by ysyplay** [comment]
这里的api设计成可变参数或者数组其实都可以，本质上都是为了把单个radio对象交给group管理。这里的api我是参考了UIAlertView 初始化方法中的可变参数方式。在实际使用过程中，你也可以添加数组的初始化方法，也很简单。
`- (instancetype)initWithTitle:(nullable NSString *)title message:(nullable NSString *)message delegate:(nullable id /*<UIAlertViewDelegate>*/)delegate cancelButtonTitle:(nullable NSString *)cancelButtonTitle otherButtonTitles:(nullable NSString *)otherButtonTitles, ... NS_REQUIRES_NIL_TERMINATION NS_EXTENSION_UNAVAILABLE_IOS("Use UIAlertController instead.")`
